const promotionsData = {
  movies: [
    {
      id: 1,
      title: "50% off on Blockbusters",
      description: "Enjoy half-price tickets for top movies this weekend.",
      image: "assets/promotions-1.png", // Updated image path
      startDate: "2024-11-17",
      endDate: "2024-11-19",
    },
    {
      id: 2,
      title: "Unlimited Movie Nights",
      description: "Monthly subscription for unlimited streaming.",
      image: "assets/promotions-2.png", // Updated image path
      startDate: "2024-11-01",
      endDate: "2024-11-30",
    },
    {
      id: 3,
      title: "Cinema Bonanza",
      description: "Free popcorn with every ticket.",
      image: "assets/promotions-3.png", // Updated image path
      startDate: "2024-11-10",
      endDate: "2024-11-15",
    },
    {
      id: 4,
      title: "Kids Movie Night",
      description: "Special discounts on family tickets.",
      image: "assets/promotions-4.png", // Updated image path
      startDate: "2024-11-18",
      endDate: "2024-11-22",
    },
    {
      id: 5,
      title: "Premiere Access",
      description: "Exclusive early access to blockbuster premieres.",
      image: "assets/promotions-5.png", // Updated image path
      startDate: "2024-11-20",
      endDate: "2024-11-30",
    },
    {
      id: 6,
      title: "Holiday Movie Specials",
      description: "Discounted tickets for holiday releases.",
      image: "assets/promotions-1.png", // Reset to image 1
      startDate: "2024-12-01",
      endDate: "2024-12-25",
    },
    {
      id: 7,
      title: "Classic Movie Marathons",
      description: "Relive the classics with marathon screenings.",
      image: "assets/promotions-2.png", // Reset to image 2
      startDate: "2024-11-25",
      endDate: "2024-11-30",
    },
    {
      id: 8,
      title: "Documentary Week",
      description: "Explore knowledge with documentary specials.",
      image: "assets/promotions-3.png", // Reset to image 3
      startDate: "2024-11-01",
      endDate: "2024-11-07",
    },
    {
      id: 9,
      title: "Indie Movie Festival",
      description: "Support indie filmmakers with festival screenings.",
      image: "assets/promotions-4.png", // Reset to image 4
      startDate: "2024-11-15",
      endDate: "2024-11-17",
    },
    {
      id: 10,
      title: "Superhero Saturdays",
      description: "Catch superhero classics every Saturday.",
      image: "assets/promotions-5.png", // Reset to image 5
      startDate: "2024-11-01",
      endDate: "2024-11-30",
    },
  ],
  events: [
    {
      id: 1,
      title: "Music Fest Discount",
      description: "Get 30% off on concert tickets.",
      image: "https://via.placeholder.com/150x100?text=Music+Fest",
      startDate: "2024-11-20",
      endDate: "2024-11-22",
    },
    {
      id: 2,
      title: "Early Bird Event Pass",
      description: "Save 20% when you book in advance.",
      image: "https://via.placeholder.com/150x100?text=Early+Bird",
      startDate: "2024-11-01",
      endDate: "2024-11-15",
    },
    {
      id: 3,
      title: "Art Festival Special",
      description: "2-for-1 entry on weekends.",
      image: "https://via.placeholder.com/150x100?text=Art+Festival",
      startDate: "2024-11-10",
      endDate: "2024-11-12",
    },
    {
      id: 4,
      title: "Food Festival",
      description: "Special offers on tasting passes.",
      image: "https://via.placeholder.com/150x100?text=Food+Fest",
      startDate: "2024-11-14",
      endDate: "2024-11-16",
    },
    {
      id: 5,
      title: "Tech Conference Discount",
      description: "Student passes available at half price.",
      image: "https://via.placeholder.com/150x100?text=Tech+Conference",
      startDate: "2024-12-01",
      endDate: "2024-12-10",
    },
    {
      id: 6,
      title: "Comedy Show Night",
      description: "Laugh out loud for less.",
      image: "https://via.placeholder.com/150x100?text=Comedy+Night",
      startDate: "2024-11-25",
      endDate: "2024-11-27",
    },
    {
      id: 7,
      title: "Book Fair Specials",
      description: "Up to 50% off on books and more.",
      image: "https://via.placeholder.com/150x100?text=Book+Fair",
      startDate: "2024-11-05",
      endDate: "2024-11-12",
    },
    {
      id: 8,
      title: "Fashion Week Preview",
      description: "Exclusive passes for fashion week previews.",
      image: "https://via.placeholder.com/150x100?text=Fashion+Week",
      startDate: "2024-11-18",
      endDate: "2024-11-21",
    },
    {
      id: 9,
      title: "Outdoor Adventure Expo",
      description: "Discounts on tickets for adventure enthusiasts.",
      image: "https://via.placeholder.com/150x100?text=Adventure+Expo",
      startDate: "2024-12-01",
      endDate: "2024-12-05",
    },
    {
      id: 10,
      title: "Charity Gala",
      description: "Support a cause with discounted gala passes.",
      image: "https://via.placeholder.com/150x100?text=Charity+Gala",
      startDate: "2024-12-10",
      endDate: "2024-12-15",
    },
  ],
  flights: [
    {
      id: 1,
      title: "Summer Getaway Deals",
      description: "Up to 40% off on flights to tropical destinations.",
      image: "https://via.placeholder.com/150x100?text=Summer+Getaway",
      startDate: "2024-06-01",
      endDate: "2024-06-30",
    },
    {
      id: 2,
      title: "Business Class Upgrade",
      description: "Exclusive upgrades for loyal customers.",
      image: "https://via.placeholder.com/150x100?text=Business+Upgrade",
      startDate: "2024-11-01",
      endDate: "2024-11-15",
    },
    {
      id: 3,
      title: "Weekend Escape Offers",
      description: "Great discounts for last-minute travelers.",
      image: "https://via.placeholder.com/150x100?text=Weekend+Escape",
      startDate: "2024-11-20",
      endDate: "2024-11-25",
    },
    {
      id: 4,
      title: "Early Bird Flight Deals",
      description: "Book early and save big.",
      image: "https://via.placeholder.com/150x100?text=Early+Bird",
      startDate: "2024-11-10",
      endDate: "2024-11-12",
    },
    {
      id: 5,
      title: "Student Travel Offers",
      description: "Special rates for students.",
      image: "https://via.placeholder.com/150x100?text=Student+Travel",
      startDate: "2024-11-01",
      endDate: "2024-11-15",
    },
    {
      id: 6,
      title: "Family Vacation Discounts",
      description: "Save more when traveling with family.",
      image: "https://via.placeholder.com/150x100?text=Family+Vacation",
      startDate: "2024-12-01",
      endDate: "2024-12-10",
    },
    {
      id: 7,
      title: "Luxury Travel Deals",
      description: "Discounted fares for first-class experiences.",
      image: "https://via.placeholder.com/150x100?text=Luxury+Travel",
      startDate: "2024-12-01",
      endDate: "2024-12-15",
    },
    {
      id: 8,
      title: "Adventure Travel Offers",
      description: "Plan your adventure trip with discounted tickets.",
      image: "https://via.placeholder.com/150x100?text=Adventure+Travel",
      startDate: "2024-11-25",
      endDate: "2024-11-30",
    },
    {
      id: 9,
      title: "Senior Citizen Discounts",
      description: "Special offers for senior travelers.",
      image: "https://via.placeholder.com/150x100?text=Senior+Discounts",
      startDate: "2024-11-10",
      endDate: "2024-11-20",
    },
    {
      id: 10,
      title: "Holiday Special Flights",
      description: "Save big on holiday season flights.",
      image: "https://via.placeholder.com/150x100?text=Holiday+Flights",
      startDate: "2024-12-20",
      endDate: "2024-12-25",
    },
  ],
};

export default promotionsData;
